# Generated by Django 5.2.9 on 2025-12-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_chat_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
