# Generated by Django 5.2.9 on 2026-01-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatroom_chatroommember_message_delete_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.JSONField(default=list),
        ),
    ]
