# Generated by Django 5.2.9 on 2026-01-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_message_video_message_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
